services:
  - type: web
    name: flask-password-generator
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.5
